ALTER TABLE `#__redshopb_product`
  MODIFY `min_sale` DOUBLE UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `max_sale` DOUBLE UNSIGNED NULL DEFAULT NULL,
  MODIFY `pkg_size` DOUBLE UNSIGNED NOT NULL DEFAULT 1;
